# This is a basic workflow to help you get started with Actions

name: CI


on:
  workflow_dispatch:
    inputs:
      env:
        description: 'Select environment to deploy'
        required: true
        default: 'preprod'
        type: choice
        options:
          - preprod
          - prod
      tag_version:
        description: 'Tag version to be deployed'
        required: true
        default: ''

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    environment:  ${{ github.event.inputs.env }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: |
           echo environment ${{ github.event.inputs.env }}
           echo '${{ env.TEST }}'

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
