# This is a basic workflow to help you get started with Actions

name: CI
run-name: ${{ github.actor }} triggered Release workflow

on:
  workflow_dispatch:
    inputs:
      schemata_branch:
        description: "Schemata branch to be used by the unit tests"
        default: master
      traser_mapping_branch:
        description: "Traser mapping files branch to be used by the unit tests"
        default: master



# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    environment:  dev

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: |
           echo schemata_branch ${{ github.event.inputs.schemata_branch }}
           echo traser_mapping_branch ${{ github.event.inputs.traser_mapping_branch }}

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
