name: Deploy to PROD
run-name: ${{ github.actor }} triggered deploy to PROD pipeline

on:
  push:
    branches:
      - "main"

jobs:
  deploy:
    #if: github.event.pull_request.merged == true
    permissions:
      contents: write
      id-token: write

    runs-on: ubuntu-latest
    environment: prod
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v3
        with:
          ref: main

      - name: Create the release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: 3
          prerelease: false
