name: Deploy to PROD
run-name: ${{ github.actor }} triggered deploy to PROD pipeline

on:
  push:
    branches:
      - "main"

jobs:
  deploy:
    #if: github.event.pull_request.merged == true
    permissions:
      contents: write
      id-token: write

    runs-on: ubuntu-latest
    environment: prod
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v3
        with:
          ref: main

      - name: Create Release
        id: create_release
        uses: comnoco/create-release-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: 4
          release_name: Release 4
          draft: false
          prerelease: false
