name: Build docker image
run-name: ${{ github.actor }} triggered Build docker image

on:
  push:
    branches:
      - "main"

jobs:
  deploy:
    permissions:
      contents: write
      id-token: write

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v3
        with:
          ref: main

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
    
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ivan123123/c_matrix_library:latest
          cache-from: type=gha
          cache-to: type=gha
